### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by SlightlyPeckish** [timmybo5/simple-weapon-base#74]
When shooting with any gun particles appear as a bunch of x's (as shown in image below)
![590830_20230206173736_1](https://user-images.githubusercontent.com/21175434/217044759-1b8927dd-d779-4802-9300-00087afc8479.png)

**Comment by timmybo5** [comment]
That's a sbox bug, restarting the game should fix that. I really hope they take a look at these uncompiled issues soon :)

**Comment by SlightlyPeckish** [comment]
Even after rebooting the issue still occurs I've played it on and off and it's always been broken particles no matter rebooting or not
